### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by krischer** [krischer/seismo_live#34]
- [ ] Finish #33  (@sebnoe @krischer)
- [ ] Docker base image (@megies)
- [ ] Auto-generate index page (@krischer)
- [ ] Public relations and 💵  (@heinerigel)

**Comment by megies** [comment]
@sebnoe i can not ever get mybinder to start, actually. Not on `master` and not on `binder_dockerfile`. Last time you said it works for you just taking long sometimes, what exactly were you doing to get it started?

![binder1](https://user-images.githubusercontent.com/1842780/67205596-54bf7b80-f410-11e9-85d1-677b837cee26.png)
![binder2](https://user-images.githubusercontent.com/1842780/67205598-54bf7b80-f410-11e9-82c8-99bce4a93540.png)

**Comment by megies** [comment]
@heinerigel @krischer @sebnoe 

Switching to a fully static install using pre-built docker images is ready now.

seismo-live can basically started in usually 40 secs to 2mins on mybinder.org:

https://mybinder.org/v2/gh/krischer/seismo_live/binder_dockerfile

I think #36 can be merged.

The way forward could be:
 - change the seismo-live website
   - move to a different host (since LRZ shuts down the current hosting next week)
   - auto-generate index page
   - change how jupyter is embedded
     - when clicking "launch a new notebook" the website can start a binder via [binderhub API](https://binderhub.readthedocs.io/en/latest/api.html) on mybinder.org in the background
     - individual notebooks in the directory tree can directly link to the notebooks by inspecting the [`ready` HTTP response](https://binderhub.readthedocs.io/en/latest/api.html#ready), e.g. linking to `https://hub.gke.mybinder.org/user/krischer-seismo_live-yhz2uk7m/notebooks/seismo_live/notebooks/Ambient%20Seismic%20Noise/Probabilistic%20Power%20Spectral%20Densities.ipynb`

Other changes can come after this step, I think..
 - jupytext setup
 - notebook testing in CI
 - fix animations and individual notebooks

**Comment by megies** [comment]
@krischer is there an easy option to have an interim website for `seismo-live.org` hosted at LRZ that will just provide a link to `https://mybinder.org/v2/gh/krischer/seismo_live/binder_dockerfile` instead of the current `tmpnbserver` getting started in LRZ cloud?
